apiVersion: v1
kind: Service
metadata:
  name: bloc11-app
  namespace: bloc11
spec:
  type: NodePort
  selector:
    app: bloc11-app
  ports:
    - port: 8000
      nodePort: 30080   # exposé sur localhost:8088 (port libéré du bloc 3)
