# Traduction des noms StatsD d'Airflow (avec des points) en métriques
# Prometheus propres (avec des labels).
mappings:
  - match: "airflow.dagrun.duration.success.*"
    name: "airflow_dagrun_duration_success"
    labels:
      dag_id: "$1"

  - match: "airflow.dagrun.duration.failed.*"
    name: "airflow_dagrun_duration_failed"
    labels:
      dag_id: "$1"

  - match: "airflow.ti.finish.*.*.*"
    name: "airflow_ti_finish"
    labels:
      dag_id: "$1"
      task_id: "$2"
      state: "$3"

  - match: "airflow.dag.*.*.duration"
    name: "airflow_task_duration"
    labels:
      dag_id: "$1"
      task_id: "$2"
