apiVersion: v1
kind: Service
metadata:
  name: bloc4-app
  namespace: bloc4
spec:
  type: NodePort
  selector:
    app: bloc4-app
  ports:
    - port: 8000
      nodePort: 30081   # exposé sur localhost:8089 (cf. infra/kind/cluster.yaml)
